---

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - '*.*'
    paths:
      - 'src/**'
      - 'tests/**'
      - '.php-cs-fixer.dist.php'
      - 'composer.*'
  pull_request:
    branches:
      - '*.*'
    paths:
      - 'src/**'
      - 'tests/**'
      - '.php-cs-fixer.dist.php'
      - 'composer.*'

name: 🔐 Dependency analysis

jobs:
  dependency-analysis:
    timeout-minutes: 4
    runs-on: ${{ matrix.os }}
    concurrency:
      cancel-in-progress: true
      group: dependency-analysis-${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
    strategy:
      fail-fast: true
      matrix:
        os:
          - ubuntu-latest
        php-version:
          - '8.2'
        dependencies:
          - locked

    steps:
      - name: 📦 Check out the codebase
        uses: actions/checkout@v5

      - name: 🛠️ Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: none, ctype, dom, json, mbstring, phar, simplexml, tokenizer, xml, xmlwriter, sockets, fileinfo, pdo
          ini-values: error_reporting=E_ALL
          coverage: none
          tools: phive

      - name: 🤖 Validate composer.json and composer.lock
        run: composer validate --ansi --strict

      - name: 📥 Install dependencies with composer
        uses: ramsey/composer-install@v3
        with:
          dependency-versions: ${{ matrix.dependencies }}

      - name: 📥 Install dependencies with phive
        uses: cycle/gh-actions/actions/phive/install@v4.0.0
        with:
          phive-home: '.phive'
          trust-gpg-keys: 0xC00543248C87FB13,0x033E5F8D801A2F8D

      - name: 🔬 Run maglnet/composer-require-checker
        run: .phive/composer-require-checker check --ansi --config-file="$(pwd)/composer-require-checker.json" --verbose
