---

on:  # yamllint disable-line rule:truthy
  pull_request:
    branches:
      - '*.*'
  push:
    branches:
      - '*.*'

name: 🔍 Continuous integration

jobs:
  code-coverage:
    timeout-minutes: 4
    runs-on: ${{ matrix.os }}
    concurrency:
      cancel-in-progress: true
      group: code-coverage-${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
    strategy:
      fail-fast: true
      matrix:
        os:
          - ubuntu-latest
        php-version:
          - '8.2'
        dependencies:
          - locked
    steps:
      - name: Install ODBC driver.
        run: |
          sudo curl https://packages.microsoft.com/config/ubuntu/$(lsb_release -rs)/prod.list | sudo tee /etc/apt/sources.list.d/mssql-release.list
          sudo ACCEPT_EULA=Y apt-get install -y msodbcsql18

      - name: 📦 Check out the codebase
        uses: actions/checkout@v5

      - name: 🛠️ Setup PHP
        uses: shivammathur/setup-php@2.30.4
        with:
          php-version: ${{ matrix.php-version }}
          extensions: mbstring, pdo, pdo_sqlite
          ini-values: error_reporting=E_ALL
          coverage: xdebug

      - name: 🤖 Validate composer.json and composer.lock
        run: composer validate --ansi --strict

      - name: 📥 Install dependencies with composer
        uses: ramsey/composer-install@v3
        with:
          dependency-versions: "highest"

      - name: 🧪 Collect code coverage with Xdebug and phpunit/phpunit
        run: composer test:cc

      - name: 📤 Upload code coverage report to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: runtime/phpunit/logs/clover.xml
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true


  arch-testing:
    timeout-minutes: 4
    runs-on: ${{ matrix.os }}
    concurrency:
      cancel-in-progress: true
      group: arch-testing-${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}-${{ matrix.php-version }}-${{ matrix.dependencies }}
    strategy:
      fail-fast: true
      matrix:
        os:
          - ubuntu-latest
        php-version:
          - '8.2'
        dependencies:
          - locked
    steps:
      - name: 📦 Check out the codebase
        uses: actions/checkout@v5

      - name: 🛠️ Setup PHP
        uses: shivammathur/setup-php@2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: mbstring, pdo, pdo_sqlite
          ini-values: error_reporting=E_ALL
          coverage: xdebug

      - name: 🤖 Validate composer.json and composer.lock
        run: composer validate --ansi --strict

      - name: 📥 Install dependencies with composer
        uses: ramsey/composer-install@v3
        with:
          dependency-versions: "highest"

      - name: 🚀 Run architecture tests
        run: composer test:arch
